# Generated by Django 3.1 on 2020-09-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Enter your Facebook URL')),
                ('linkedin', models.URLField(blank=True, help_text='Enter your LinkedIn URL')),
                ('twitter', models.URLField(blank=True, help_text='Enter your Twitter URL')),
                ('youtube', models.URLField(blank=True, help_text='Enter your YouTube URL')),
                ('instagram', models.URLField(blank=True, help_text='Enter your Instagram URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_button_text', models.CharField(blank=True, default='Form', help_text='Enter the text that will appear on the contact button', max_length=32, null=True)),
                ('call_button_text', models.CharField(blank=True, default='Call', help_text='Enter the text that will appear on the call button', max_length=32, null=True)),
                ('call_button_number', models.CharField(blank=True, default=None, help_text='Enter the number to call', max_length=32, null=True)),
                ('email_display_text', models.CharField(blank=True, help_text='Enter the email address that will appear for email contact', max_length=32, null=True)),
                ('email_address', models.CharField(blank=True, help_text='Enter the email address that will be used for email contact', max_length=32, null=True)),
                ('phone_display_text', models.CharField(blank=True, help_text='Enter the number that will appear for phone contact', max_length=32, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Enter the phone number that will be used for phone contact', max_length=32, null=True)),
                ('contact_button_page', models.ForeignKey(blank=True, help_text='Select the contact form page to link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
