version: '3.7'

services:

  redis:
    image: redis:latest
    volumes:
        - data-redis:/data
    expose:
      - "6379"
    ports:
      - "127.0.0.1:${RDPORT}:6379"
    networks:
        - internal_net
    restart: always

  db:
    image: postgres:latest
    environment:
      - DBHOST=${DBHOST}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
        - data-pgdata:/var/lib/postgresql/data
    networks:
      - internal_net
    expose:
      - "5432"
    ports:
      - "127.0.0.1:${DBPORT}:5432"
    restart: always

volumes:
  data-redis:
  data-pgdata:

networks:
  internal_net:
