version: '3.5'

services:

  redis:
    image: redis:latest
    volumes:
      - data-redis:/data
    expose:
      - "6379"
    ports:
      - "7379:6379"
    networks:
        - internal_net
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
        - data-pgdata:/var/lib/postgresql/data
    networks:
      - internal_net
    expose:
      - "5432"
    ports:
      - "6432:5432"
    restart: always

volumes:
  data-redis:
  data-pgdata:

networks:
  internal_net:
