# Generated by Django 3.1 on 2020-09-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('contact', '0002_auto_20200901_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_image',
            field=models.ForeignKey(blank=True, help_text='Image will be cropped to 580px by 355px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
