# Generated by Django 3.0.8 on 2020-07-27 03:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_title', models.CharField(blank=True, help_text='The main display title for this page', max_length=255, null=True)),
                ('page_banner_caption', models.CharField(blank=True, help_text='Caption for the banner (options)', max_length=255, null=True)),
                ('page_body', wagtail.core.fields.RichTextField(blank=True, help_text='Page text')),
                ('article', wagtail.core.fields.StreamField([('article', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='Article heading (optional)', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image (optional)', required=False)), ('article', wagtail.core.blocks.RichTextBlock(help_text='Article Text')), ('url', wagtail.core.blocks.URLBlock(help_text='Related link (optional)', required=False))]))])),
                ('page_banner', models.ForeignKey(help_text='A banner for the top of the page (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page_tags', taggit.managers.TaggableManager(blank=True, help_text='Tags used to search for this page', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article Page',
                'verbose_name_plural': 'Article Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CMSArticleWithCarouselPage',
            fields=[
                ('articlepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.ArticlePage')),
            ],
            options={
                'verbose_name': 'Article Page With Carousel',
                'verbose_name_plural': 'Article Pages With Carousel',
            },
            bases=('cms.articlepage',),
        ),
        migrations.CreateModel(
            name='CarouselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('carousel_image', models.ForeignKey(help_text='Image to appear in the carousel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(help_text='Page model on which this carousel appears', on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='cms.CMSArticleWithCarouselPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
