# Generated by Django 3.1.1 on 2020-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspage',
            name='display_title',
            field=models.BooleanField(default=True),
        ),
    ]
