# Generated by Django 3.1.1 on 2020-09-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_cmspage_display_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimage',
            old_name='block',
            new_name='parent_pg',
        ),
    ]
