# Generated by Django 3.1.1 on 2020-09-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20200905_0006'),
        ('cms', '0008_auto_20200905_1255'),
    ]

    operations = [
    ]
