# Generated by Django 3.1.1 on 2020-09-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20200905_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='carousel_interval',
            field=models.IntegerField(default=12000, help_text='Keep visible for time in milliseconds'),
        ),
    ]
