# Generated by Django 3.1.6 on 2021-02-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-2, 'Unknown'), (-1, 'Canceled'), (0, 'New Order'), (1, 'Ready for Payment'), (2, 'Accepting Payment'), (3, 'Processing Payment'), (4, 'Payment Completed'), (5, 'Dispatched'), (6, 'Completed')], default=0),
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, help_text='date and time created')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=10)),
                ('session_id', models.TextField(help_text='Transaction session id')),
                ('milestone', models.IntegerField(choices=[(0, 'created'), (1, 'accepted'), (2, 'cancelled')], help_text='Action for this esssion')),
                ('session_data', models.TextField(blank=True, help_text='Verbose session data', null=True)),
                ('order', models.ForeignKey(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order')),
            ],
        ),
    ]
