# Generated by Django 3.1.6 on 2021-02-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210214_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'ordering': ('-dt_created', 'milestone')},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-2, 'Unknown'), (-1, 'Cancelled'), (0, 'New Order'), (1, 'Ready for Payment'), (2, 'Accepting Payment'), (3, 'Processing Payment'), (4, 'Payment Completed'), (5, 'Dispatched'), (6, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='milestone',
            field=models.IntegerField(choices=[(-1, 'unknown'), (0, 'created'), (1, 'accepted'), (2, 'cancelled'), (3, 'confirmed')], help_text='Action for this esssion'),
        ),
    ]
